# Generated by Django 3.1.3 on 2020-11-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICALinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='data_app.icacomponent')),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_from_prev', to='data_app.icacomponent')),
                ('prev', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_from_next', to='data_app.icacomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ICAImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_topomap', models.ImageField(null=True, upload_to='images/')),
                ('img_spectrum', models.ImageField(null=True, upload_to='images/')),
                ('img_epochs_image', models.ImageField(null=True, upload_to='images/')),
                ('ic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data_app.icacomponent')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_components', models.IntegerField(default=0)),
                ('agreement', models.FloatField(default=0)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='data_app.dataset')),
            ],
            options={
                'verbose_name_plural': 'DatasetStats',
            },
        ),
    ]
