# Generated by Django 3.1.3 on 2020-11-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ICAComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('ica_weights', models.JSONField()),
                ('ica_data', models.JSONField()),
                ('sfreq', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('images_calculated', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ics', to='main_app.dataset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'subject', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='ICAImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_topomap', models.ImageField(upload_to='images/')),
                ('ic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.icacomponent')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_components', models.IntegerField(default=0)),
                ('agreement', models.FloatField(default=0)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main_app.dataset')),
            ],
            options={
                'verbose_name_plural': 'DatasetStats',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_brain', models.BooleanField(default=False)),
                ('flag_eyes', models.BooleanField(default=False)),
                ('flag_muscles', models.BooleanField(default=False)),
                ('flag_heart', models.BooleanField(default=False)),
                ('flag_line_noise', models.BooleanField(default=False)),
                ('flag_ch_noise', models.BooleanField(default=False)),
                ('comment', models.TextField(default='')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.icacomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
