# Generated by Django 3.1.3 on 2020-11-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='component',
            new_name='ic',
        ),
    ]
