# Generated by Django 3.1.2 on 2020-11-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20201102_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetstats',
            options={'verbose_name_plural': 'DatasetStats'},
        ),
        migrations.AddField(
            model_name='dataset',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='icacomponent',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ics', to='main_app.dataset'),
        ),
        migrations.AlterField(
            model_name='icacomponent',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
