# Generated by Django 3.1.3 on 2020-11-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201107_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='user',
        ),
    ]
