# Generated by Django 3.1.3 on 2020-11-07 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_annotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('ic', 'user')},
        ),
    ]
