# Generated by Django 3.1.3 on 2020-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201107_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='icaimages',
            name='img_epochs_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='icaimages',
            name='img_spectrum',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='icaimages',
            name='img_topomap',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
