# Generated by Django 3.1.3 on 2020-11-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201111_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICALinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main_app.icacomponent')),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_from_prev', to='main_app.icacomponent')),
                ('prev', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_from_next', to='main_app.icacomponent')),
            ],
        ),
    ]
