# Generated by Django 3.1.3 on 2020-11-16 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ICAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ica_weights', models.JSONField()),
                ('ica_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ICAComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('sfreq', models.FloatField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ic', to='data_app.icadata')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ics', to='data_app.dataset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'subject', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_brain', models.BooleanField(default=False)),
                ('flag_eyes', models.BooleanField(default=False)),
                ('flag_muscles', models.BooleanField(default=False)),
                ('flag_heart', models.BooleanField(default=False)),
                ('flag_line_noise', models.BooleanField(default=False)),
                ('flag_ch_noise', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('ic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_app.icacomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ic', 'user')},
            },
        ),
    ]
