# Generated by Django 3.1.3 on 2020-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icadata',
            name='ica_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='icadata',
            name='ica_weights',
            field=models.TextField(),
        ),
    ]
