# Generated by Django 3.1.3 on 2020-12-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_auto_20201124_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='flag_alpha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_eyes_h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_eyes_v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_mu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
