# Generated by Django 3.1.3 on 2020-12-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_auto_20201205_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
