# Generated by Django 3.1.3 on 2021-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_dataset_annotation_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='flag_movement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_muscles_and_movement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='flag_noise',
            field=models.BooleanField(default=False),
        ),
    ]
