# Generated by Django 3.1.3 on 2021-07-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_auto_20210710_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='flag_eyes_blinks',
            field=models.BooleanField(default=False),
        ),
    ]
